addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 77a97b25-d448-462f-9504-6d6a27b0098f
after_success:
- ./df-build.sh
before_script:
- rm -rf $HOME/.m2/repository/org/apache/accumulo
- echo "<settings xmlns='http://maven.apache.org/SETTINGS/1.0.0'><mirrors><mirror><id>secure-central</id><url>https://repo.maven.apache.org/maven2</url><mirrorOf>central</mirrorOf></mirror></mirrors></settings>"
  > $HOME/settings-custom.xml
cache:
  directories:
  - $HOME/.m2
install: true
jdk:
- oraclejdk8
language: java
notifications: {}
script: mvn --settings $HOME/settings-custom.xml clean verify -DskipITs
# Modified by Insights Service at 2016-05-20 06:19:11.278325
